module.exports = {
  DOC: '$doc',
  DOCS: '$docs',
  MODEL: '$model',
  MODELS: '$models',
  NEW_DOC: '$new_doc',
  OLD_DOC: '$old_doc',
  NEW_OLD_DOC: '$new_old_doc',
  NEW_MODEL: '$new_model',
  OLD_MODEL: '$old_model',
  NEW_OLD_MODEL: '$new_old_model',
  NEW_DOCS: '$new_docs',
  OLD_DOCS: '$old_docs',
  NEW_OLD_DOCS: '$new_old_docs',
  NEW_MODELS: '$new_models',
  OLD_MODELS: '$old_models',
  NEW_OLD_MODELS: '$new_old_models',
}