sudo: required

language: node_js
node_js:
  - 8.11.4

services:
  - docker

before_install:
  - docker pull arangodb
  - docker run -d -e ARANGO_NO_AUTH=1 -p 8529:8529 arangodb
  - docker ps -a

after_success: npm run coverage  
