module.exports = {
  ERRORS: {
    ALREADY_CONNECTED: 'Connection already established',
    NOT_CONNECTED: 'Not connected to database',
    COLLECTION_NOT_FOUND: 'Collection not found: ',
    MODEL_NOT_FOUND: 'Model not found: '
  },
  RESERVED_WORDS: [
    'FOR',
    'RETURN',
    'FILTER',
    'SEARCH',
    'SORT',
    'LIMIT',
    'LET',
    'COLLECT',
    'INSERT',
    'UPDATE',
    'REPLACE',
    'REMOVE',
    'UPSERT',
    'AGGREGATE',
    'ALL',
    'AND',
    'ANY',
    'ASC',
    'COLLECT',
    'DESC',
    'DISTINCT',
    'FALSE',
    'FILTER',
    'FOR',
    'GRAPH',
    'IN',
    'INBOUND',
    'INSERT',
    'INTO',
    'LET',
    'LIKE',
    'LIMIT',
    'NONE',
    'NOT',
    'NULL',
    'OR',
    'OUTBOUND',
    'REMOVE',
    'REPLACE',
    'RETURN',
    'SHORTEST_PATH',
    'SORT',
    'TRUE',
    'UPDATE',
    'UPSERT',
    'WITH'
  ],
  MODEL_READY: 'Model ready'
}
